name: Build and Deploy Unity Game to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    - name: Cache Unity Library
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Build Unity Project
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: WebGL
        buildName: Roll-a-Ball
        buildsPath: build
        
    - name: Create optimized index.html for GitHub Pages
      run: |
        cat > build/WebGL/Roll-a-Ball/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en-us">
        <head>
            <meta charset="utf-8">
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
            <title>Roll-a-Ball by Juan Gabriel</title>
            <link rel="shortcut icon" href="TemplateData/favicon.ico">
            <link rel="stylesheet" href="TemplateData/style.css">
            <style>
                body {
                    font-family: 'Arial', sans-serif;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    margin: 0;
                    padding: 20px;
                }
                .header {
                    text-align: center;
                    color: white;
                    margin-bottom: 20px;
                }
                .license {
                    position: absolute;
                    top: 10px;
                    right: 10px;
                    color: white;
                    font-size: 14px;
                    background: rgba(0,0,0,0.3);
                    padding: 10px;
                    border-radius: 5px;
                }
                .game-container {
                    background: white;
                    border-radius: 10px;
                    padding: 20px;
                    box-shadow: 0 10px 30px rgba(0,0,0,0.3);
                    max-width: 1000px;
                    margin: 0 auto;
                }
                .controls {
                    margin-top: 20px;
                    padding: 15px;
                    background: #f5f5f5;
                    border-radius: 5px;
                }
                .controls h3 {
                    margin-top: 0;
                    color: #333;
                }
                .controls ul {
                    margin: 10px 0;
                    padding-left: 20px;
                }
                .controls li {
                    margin: 5px 0;
                }
            </style>
        </head>
        <body>
            <div class="license">
                Created by: Juan Gabriel<br>
                License: 1200221
            </div>
            
            <div class="header">
                <h1>Roll-a-Ball by Juan Gabriel</h1>
                <p>A 3D Ball Rolling Adventure with 10 Challenging Levels</p>
            </div>
            
            <div class="game-container">
                <div id="unity-container" class="unity-desktop">
                    <canvas id="unity-canvas" width=960 height=600></canvas>
                    <div id="unity-loading-bar">
                        <div id="unity-logo"></div>
                        <div id="unity-progress-bar-empty">
                            <div id="unity-progress-bar-full"></div>
                        </div>
                    </div>
                    <div id="unity-warning"> </div>
                    <div id="unity-footer">
                        <div id="unity-webgl-logo"></div>
                        <div id="unity-fullscreen-button"></div>
                        <div id="unity-build-title">Roll-a-Ball by Juan Gabriel</div>
                    </div>
                </div>
                
                <div class="controls">
                    <h3>🎮 Game Controls</h3>
                    <ul>
                        <li><strong>WASD Keys or Arrow Keys:</strong> Move the ball</li>
                        <li><strong>Mouse:</strong> Navigate menus</li>
                        <li><strong>ESC:</strong> Pause game</li>
                    </ul>
                    
                    <h3>🎯 Objective</h3>
                    <ul>
                        <li>Collect all triangles and cylinders in each level</li>
                        <li>Complete each level within 120 seconds</li>
                        <li>Avoid falling off platforms</li>
                        <li>Navigate through mazes and avoid moving obstacles</li>
                    </ul>
                    
                    <h3>🏆 Level Overview</h3>
                    <ol>
                        <li><strong>Tutorial</strong> - Learn the basics</li>
                        <li><strong>Speed Course</strong> - Fast-paced collection</li>
                        <li><strong>Narrow Paths</strong> - Precision platforming</li>
                        <li><strong>The Maze</strong> - Navigate complex paths</li>
                        <li><strong>Moving Obstacles</strong> - Avoid dynamic challenges</li>
                        <li><strong>Elevation</strong> - Multi-level collection</li>
                        <li><strong>Time Crunch</strong> - Reduced timer challenge</li>
                        <li><strong>Spiral Challenge</strong> - Circular maze pattern</li>
                        <li><strong>The Gauntlet</strong> - Combined challenges</li>
                        <li><strong>Final Boss</strong> - Ultimate challenge</li>
                    </ol>
                </div>
            </div>
            
            <script>
                var container = document.querySelector("#unity-container");
                var canvas = document.querySelector("#unity-canvas");
                var loadingBar = document.querySelector("#unity-loading-bar");
                var progressBarFull = document.querySelector("#unity-progress-bar-full");
                var fullscreenButton = document.querySelector("#unity-fullscreen-button");
                var warningBanner = document.querySelector("#unity-warning");

                function unityShowBanner(msg, type) {
                    function updateBannerVisibility() {
                        warningBanner.style.display = warningBanner.children.length ? 'block' : 'none';
                    }
                    var div = document.createElement('div');
                    div.innerHTML = msg;
                    warningBanner.appendChild(div);
                    if (type == 'error') div.style = 'background: red; padding: 10px;';
                    else {
                        if (type == 'warning') div.style = 'background: yellow; padding: 10px;';
                        setTimeout(function() {
                            warningBanner.removeChild(div);
                            updateBannerVisibility();
                        }, 5000);
                    }
                    updateBannerVisibility();
                }

                var buildUrl = "Build";
                var loaderUrl = buildUrl + "/Roll-a-Ball.loader.js";
                var config = {
                    dataUrl: buildUrl + "/Roll-a-Ball.data",
                    frameworkUrl: buildUrl + "/Roll-a-Ball.framework.js",
                    codeUrl: buildUrl + "/Roll-a-Ball.wasm",
                    streamingAssetsUrl: "StreamingAssets",
                    companyName: "Juan Gabriel",
                    productName: "Roll-a-Ball",
                    productVersion: "1.0",
                    showBanner: unityShowBanner,
                };

                if (/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)) {
                    container.className = "unity-mobile";
                    config.devicePixelRatio = 1;
                    unityShowBanner('WebGL builds are not supported on mobile devices.');
                } else {
                    canvas.style.width = "960px";
                    canvas.style.height = "600px";
                }
                
                loadingBar.style.display = "block";

                var script = document.createElement("script");
                script.src = loaderUrl;
                script.onload = () => {
                    createUnityInstance(canvas, config, (progress) => {
                        progressBarFull.style.width = 100 * progress + "%";
                    }).then((unityInstance) => {
                        loadingBar.style.display = "none";
                        fullscreenButton.onclick = () => {
                            unityInstance.SetFullscreen(1);
                        };
                    }).catch((message) => {
                        alert(message);
                    });
                };
                document.body.appendChild(script);
            </script>
        </body>
        </html>
        EOF

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/WebGL/Roll-a-Ball
        cname: # Add your custom domain here if you have one
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WebGL-Build
        path: build/WebGL/Roll-a-Ball 


git init
git add .
git commit -m "Upload game"
git branch -M main
git remote add origin git@github.com:jgtavarez/roll-a-ball.git
git push -u origin main